from flask_openapi3 import Tag
from infra.constants.texts import (
    NAME_TAG_DOCUMENTATION,
    NAME_STATE_TAG,
    NAME_CITY_TAG,
    NAME_BANK_TAG,
    NAME_BANK_AGENCIES_TAG,
    NAME_BANK_ACCOUNTS_TAG,
    NAME_PEOPLE_TAG,
    NAME_ADRESSES_TAG,
    NAME_PHYSICAL_TAG,
    NAME_MOVIMENT_TAG,
    DESCRIPTION_TAG_DOCUMENTATION,
    DESCRIPTION_STATE_TAG,
    DESCRIPTION_CITY_TAG,
    DESCRIPTION_BANK_TAG,
    DESCRIPTION_BANK_AGENCIES_TAG,
    DESCRIPTION_BANK_ACCOUNTS_TAG,
    DESCRIPTION_PEOPLE_TAG,
    DESCRIPTION_ADRESSES_TAG,
    DESCRIPTION_PHYSICAL_TAG,
    DESCRIPTION_MOVIMENT_TAG,
)

# Defining tags
home_tag = Tag(
    name=NAME_TAG_DOCUMENTATION,
    description=DESCRIPTION_TAG_DOCUMENTATION,
)
state_tag = Tag(name=NAME_STATE_TAG, description=DESCRIPTION_STATE_TAG)
city_tag = Tag(name=NAME_CITY_TAG, description=DESCRIPTION_CITY_TAG)
bank_tag = Tag(name=NAME_BANK_TAG, description=DESCRIPTION_BANK_TAG)
bank_agencies_tag = Tag(
    name=NAME_BANK_AGENCIES_TAG,
    description=DESCRIPTION_BANK_AGENCIES_TAG,
)
bank_accounts_tag = Tag(
    name=NAME_BANK_ACCOUNTS_TAG,
    description=DESCRIPTION_BANK_ACCOUNTS_TAG,
)
people_tag = Tag(name=NAME_PEOPLE_TAG, description=DESCRIPTION_PEOPLE_TAG)
Adresses_tag = Tag(name=NAME_ADRESSES_TAG, description=DESCRIPTION_ADRESSES_TAG)
Physical_tag = Tag(name=NAME_PHYSICAL_TAG, description=DESCRIPTION_PHYSICAL_TAG)
Moviment_tag = Tag(name=NAME_MOVIMENT_TAG, description=DESCRIPTION_MOVIMENT_TAG)
